#dist: trusty
language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: ceciliacal
    token: 331a1df367982550e16360321497cab14c6a817e

install: 
  - mvn clean install -q -DskipTests=true 

script:
  - mvn clean verify sonar:sonar  -Dsonar.projectKey=ceciliacal_bookkeeper 
