#dist: trusty
language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: gulixciurli
    token: 7ea17b709914577cbb0048863aff519966af4b07

install: 
  - mvn clean install -q -DskipTests=true 

script:
  - mvn clean verify sonar:sonar  -Dsonar.projectKey=gulixciurli_bookkeeper2
